#!/bin/bash

if [ -e $HOME/.FVErc ]; then 
	source $HOME/.FVErc
	FVErc="$HOME/.FVErc"
	source "$FVEBINDIR"/FVEcomFncs
elif [ -e /etc/FVErc ]; then
	source /etc/FVErc
	FVErc="/etc/FVErc"
	source "$FVEBINDIR"/FVEcomFncs
else
	FVErc="ERROR"
fi

if [ ! -e "$CLOUDFLARESECRETSFILE" ]; then
    errorPrint "CloudFlare cred file was not found"
    exit 1
fi

sudo certbot \
    -a dns-cloudflare \
    --dns-cloudflare-credentials "$CLOUDFLARESECRETSFILE" \
    --preferred-challenges dns-01 \
    --server https://acme-v02.api.letsencrypt.org/directory \
    --dns-cloudflare-propagation-seconds 120 \
    --agree-tos \
    --no-eff-email \
    --no-redirect \
    -m "$CFMAIL" \
    -d $(hostname -f)

sudo systemctl restart lighttpd.service 
