#!/bin/bash

ERRORICON="/usr/share/icons/oxygen/64x64/status/dialog-error.png"
INFOICON="/usr/share/icons/oxygen/64x64/status/dialog-information.png"

function printHelp() {
	
	checkStatusHalter
	echo -e "\nusage: `basename $0` CMD [-F]
 CMDs: 
  * enable -- enables to halt the system via `basename $0`
    enable -F -- when once disabled, the -F parameter must be
                 used to overide and force enabling of `basename $0`
  * disable -- disables to halt the system via `basename $0`
  * stopSystem -- issue to halt the system (if allowed)
"
exit 0
}

function enableHalter(){
	if [ "$FORCEENABLE" = "1" ]; then
		echo "WARNING! Force enable was used!!!"
		echo enable > /tmp/.halter
	fi
	if [  -e /tmp/.halter ]; then
		if [ `cat /tmp/.halter` = "disable" ]; then
			echo "FVEhalter was manually disabled, use -F to overide"
			return 1
		fi
	fi
	if [ ! -e /tmp/.halter ]; then 
		if [ `cat /proc/uptime | awk  -F '.' '{print $1}'` -gt 300 ]; then
			echo enable > /tmp/.halter
			
		else
			echo "Too soon to enable the FVEhalter"
		fi
	fi
}

function disableHalter(){
	rm -f /tmp/.halter.at
	echo disable > /tmp/.halter
}

function checkStatusHalter(){
	if [ ! -e /tmp/.halter ]; then
		echo "Disabled, config file does not exist"
		return 1
	fi
	if [ `grep enable /tmp/.halter` ]; then
		echo "`basename $0` is ENABLED"
		return 0
	fi
	if [ `grep disable /tmp/.halter` ]; then
		echo "`basename $0` is disabled by configuration"
		return 1
	fi
	echo "`basename $0` is disabled"
	return 1 
}


function stopSystemHltrPLAN(){
	if ( `checkStatusHalter 1> /dev/null` ); then
		if [ ! -e /tmp/.halter.at ]; then
			echo "$0 stopSystemNOW" > /tmp/.halter.at
			at now +1 minutes -f /tmp/.halter.at
			echo 1 > /tmp/.halter.at
		fi
		#wall "System will be halted in `cat /tmp/.halter.at` min. To disable run 'FVEhalter disable'"
		#echo `expr $(cat /tmp/.halter.at) - 1 ` > /tmp/.halter.at
	fi
}

function stopSystemHltrNOW(){
	if ( `checkStatusHalter 1> /dev/null` ); then
		$0 disable
		systemctl poweroff
	fi
}

function printStatus() {
	if ( `checkStatusHalter` ); then
		echo "`basename $0` is ENABLED"
	else
		echo "`basename $0` is disabled"
	fi
	return 0
}




if [ "$1" = '-h' -o "$1" = "--help" -o "$#" = "0" ]; then
	printHelp
	exit
fi

if [ "$1" = enable -a "$2" = "-F" ]; then
	FORCEENABLE=1
fi

case $1 in
	'status') checkStatusHalter; exit 0 ;;
	'enable') enableHalter  ;;
	'disable') disableHalter ;;
	'stopSystem') stopSystemHltrPLAN;;
	'stopSystemNOW') stopSystemHltrNOW;;
	*) echo "Unknown parametr" ;;
esac

checkStatusHalter
