#!/bin/bash

# shellcheck disable=SC1091
if [ -e "$HOME"/.FVErc ]; then 
	source "$HOME"/.FVErc
	FVErc="$HOME/.FVErc"
	source "$FVEBINDIR"/FVEcomFncs
elif [ -e /etc/FVErc ]; then
	source /etc/FVErc
	FVErc="/etc/FVErc"
	source "$FVEBINDIR"/FVEcomFncs
else
	FVErc="ERROR"
fi

while true; do
	#echo "running FVEread"	
	"$FVEBINDIR"/FVEread
	#echo "sleep"
	sleep 5
done
