#!/bin/bash

source ~/.FVErc
source "$FVEBINDIR"/FVEcomFncs

OPTCFGFILE=$OPTCFGFILE.2
OPTCFGLOWFILE="$CFGDIR"/FVEoptRun.low.cfg
source $OPTCFGLOWFILE

function updateEnergy() {
	ENERGYBUCKET=$(expr $ENERGYBUCKET - $1)
	if [ $ENERGYBUCKET -lt 0 ]; then
		ENERGYBUCKET=0
	fi
	verbPrint "Remaining energy = $ENERGYBUCKET"
}


function getDeviceNumber() {
	#usage: getDeviceNumber $COMPONENT
	local COMPONENT=$1
	debugPrint "Getting device number for: $COMPONENT"
	DEVICENUM=$( grep -B1 $COMPONENT /etc/tellstick.conf | head -1 | awk '{print $NF}')
}

function checkTDstatus() {
	local TDSTATUS=`sudo service telldusd status | tr -d '!' `
	if [  "$TDSTATUS" = "telldusd is not running ... failed" ]; then
		echo "`date +%Y/%M/%d-%H:%M:%S` - Seems telldusd is down? Restarting"
		sudo service telldusd start 
		sudo service telldusd status
		echo ====
	fi
	
	> "$TMPDIR"/FVE.statuses
	tdtool -l > "$TMPDIR"/FVE.statuses
}

function printHelp() {
	echo -e "\nusage: `basename $0` [OPTIONS]
	-v         talky output
	--debug    tells everything it knows
	-f|--force force to send the on/off command despite of real status.
"
exit 0
}

function getAvrg() {
	#Will make average production in last 10 minutes (last 10 lines)

	if [ $OFF ]; then
		AVRG=0
	else
		AVRG=$(expr $(expr $(tail -10 $HISTORYFILE | awk '{print $2}' | sed '/^$/d' | sed ':a;N;$!ba;s/\n/ + /g')) / $(tail -10 $HISTORYFILE | awk '{print $2}' | sed '/^$/d' | wc -l) )	
	fi
	debugPrint "Avrg is: $AVRG"
}

function checkUptime() {
	UPTIME=$(cat /proc/uptime | awk -F '.' '{print $1}')
	if [ $UPTIME -lt 660 ]; then
		OFF='Y'
		FORCE='Y'
	fi
}

function getTemperature() {
	TEMPERATURE=60
	verbPrint "Temperature on thermal devices is $TEMPERATURE"
}

function getLowTarifInfo() {
	#returns if now we are in Low tarif or not and eventually what low tarif (1st part, 2nd part...)
	
	ISLOWTARIF=N
	LOWTARIFNUM=''
	local LOWTARIFN
	local TIMEDATEHHmm=$(date +%H%M)
	
	#Parse lowtarif config
	for LOWTARIFN in $(seq 0 $(expr $VALLOWTARIFS - 1)); do
		if [ ${VALLOWTARIF_STARTS[$LOWTARIFN]} -lt $TIMEDATEHHmm -a $TIMEDATEHHmm -lt ${VALLOWTARIF_STOPS[$LOWTARIFN]} ]; then
			verbPrint "Now we are in Low Tarif time: ${VALLOWTARIF_STARTS[$LOWTARIFN]} < $TIMEDATEHHmm < ${VALLOWTARIF_STOPS[$LOWTARIFN]} "
			ISLOWTARIF=Y
			LOWTARIFNUM=$LOWTARIFN
			break
		fi
	done
	debugPrint "LowTarif ID: $LOWTARIFNUM: LowTarif=$ISLOWTARIF"
}



function parseThermalDevice() {
DEVICEN=-1
	while read LNDEVICEID LNTYPE LNDEVICE LNCONSUMPTION LNTIME0 LNTIME1 LNSTARTTEMP LNSTOPTEMP ; do 
		((++DEVICEN))
		debugPrint "$LNDEVICEID $LNTYPE $LNDEVICE $LNCONSUMPTION $LNTIME0 $LNTIME1 $LNSTARTTEMP $LNSTOPTEMP"
		DEVICEID[$DEVICEN]=$LNDEVICEID
		TYPE["$DEVICEN"]=$LNTYPE
		DEVICE["$DEVICEN"]=$LNDEVICE
		CONSUMPTION["$DEVICEN"]=$LNCONSUMPTION
		TIME0["$DEVICEN"]=$LNTIME0
		TIME1["$DEVICEN"]=$LNTIME1
		STARTTEMP["$DEVICEN"]=$LNSTARTTEMP
		STOPTEMP["$DEVICEN"]=$LNSTOPTEMP
	done < <( cat "$OPTCFGFILE" | grep -v \# | grep thermal)

	###TEST
	if [ $DEBUG ]; then
		for i in `seq 0 $DEVICEN`; do
			echo "ID$i: ${DEVICEID[$i]}"
			echo "TYPE$i: ${TYPE["$i"]}"
			echo "NAME$i: ${DEVICE["$i"]}"
			echo "CONS$i: ${CONSUMPTION["$i"]}"
			echo "TIM1$i: ${TIME0["$i"]}"
			echo "TIM2$i: ${TIME1["$i"]}"
			echo "RTTM$i: ${STARTTEMP["$i"]}"
			echo "TPTM$i: ${STOPTEMP["$i"]}"
		done
	fi
	###ENDTEST
}

function getUptimeOfDevice() {
	local DEVICE="$1"
	local DEVICEDATAFILE="$FVEDATADIR"/"$DEVICE"."$TIMEDATE_YYYYMM"
	local DEVICEUPTIME=$(grep "$TIMEDATE_YYYYMMDD".*1$ $DEVICEDATAFILE | sort -u | wc -l)
	debugPrint "Device $DEVICE was up for $DEVICEUPTIME mins"
	return $DEVICEUPTIME
}

function whatDevicesShouldBeUpNODT() {
	TIMETARIF="TIME$LOWTARIFNUM[@]"
	local LOCALDEVICEID=-1
	while read DESIREDUPTIME; do
		((++LOCALDEVICEID))
		if [ $DESIREDUPTIME -gt 0 ]; then
			debugPrint "Device ${DEVICE["$LOCALDEVICEID"]} in this lowtarif n.$LOWTARIFNUM should be up for $DESIREDUPTIME mins."
			getUptimeOfDevice ${DEVICE["$LOCALDEVICEID"]}
			local UPTIME="$?"
			if [ "$UPTIME" -lt "$DESIREDUPTIME" ]; then
				verbPrint "Device ${DEVICE["$LOCALDEVICEID"]} was up for $UPTIME mins, but required is $DESIREDUPTIME."				
				STARTSTOPDEVICES["${DEVICEID["$LOCALDEVICEID"]}"]=ON
				updateEnergy ${CONSUMPTION["$LOCALDEVICEID"]}
			else
				verbPrint "Device ${DEVICE["$LOCALDEVICEID"]} was up for $UPTIME, that is more than $DESIREDUPTIME mins, not starting now"
				STARTSTOPDEVICES["${DEVICE["$LOCALDEVICEID"]}"]=OFF
			fi
		else
			verbPrint "Device ${DEVICE["$LOCALDEVICEID"]} in this lowtarif n.$LOWTARIFNUM should not be up"
			STARTSTOPDEVICES["${DEVICE["$LOCALDEVICEID"]}"]=OFF
		fi
	done < <(echo ${!TIMETARIF} | tr ' ' '\n')
	return 0
}

function whatDevicesShouldBeUpDT() {
	getTemperature

	if [ $TEMPERATURE -lt $VALLOWTARIFMINTEMP ]; then
		verbPrint "Temperature in thermal device is lower than minimum requested. $TEMPERATURE < $VALLOWTARIFMINTEMP"
		local LOCALDEVICEID=-1
		while read DEVICENAME; do
			((++LOCALDEVICEID))
			verbPrint "STARTING DEVICE $DEVICENAME"
			STARTSTOPDEVICES["${DEVICEID[$LOCALDEVICEID]}"]=ON
			updateEnergy ${CONSUMPTION["$LOCALDEVICEID"]}
		done < <( cat "$OPTCFGFILE" | grep -v \# | awk /thermal/'{print $3}' ) 
	else 
		verbPrint "Temperature in thermal device is over minimum requested. $VALLOWTARIFMINTEMP < $TEMPERATURE"
	fi
}

function manageThermalDevices {
	parseThermalDevice #done
	if [ "$ISLOWTARIF" = "Y" ]; then
	verbPrint "LowTarif time is enabled"
		if [ "$DIRECTTEMP" = "ON" ]; then
			verbPrint "DirectTemp is ON, enabling temperature-based configuration"
			whatDevicesShouldBeUpDT
		elif [ "$DIRECTTEMP" = "OFF" ]; then
			verbPrint "DirectTemp is OFF, enabling time-based configuration"
			whatDevicesShouldBeUpNODT
		else
			echo "Not able parse configuration, quitting"
			exit 1
		fi
	else
		verbPrint "Out of lowtarif"
	fi	
}

function manageGeneralDevices() {
	return 0
}

function enableDisableDevices() {
	return 0
}

function initDeviceTable() {
	verbPrint "Table STARTSTOPDEVICES[] is being initialized with values:"
	while read ID VOID DEVICENAME VOID; do
		STARTSTOPDEVICES["$ID"]=OFF
		verbPrint "$DEVICENAME = ${STARTSTOPDEVICES["$ID"]}"
	done < <( cat "$OPTCFGFILE" | grep -v \# | sed /^$/d)
	
}

function checkDeviceTable() {
	verbPrint "Current status of table STARTSTOPDEVICES[]:"
	while read ID VOID DEVICENAME VOID; do
		verbPrint "$DEVICENAME = ${STARTSTOPDEVICES["$ID"]}"
	done < <( cat "$OPTCFGFILE" | grep -v \# | sed /^$/d)
}

mainLoop() {
	initDeviceTable
	getLowTarifInfo
	manageThermalDevices
	#~ manageGeneralDevices
	#~ enableDisableDevices
	checkDeviceTable
}



VERBOUT="2>/dev/null"
FORCE='N'
OFF=''
VERB=''
DEBUG=''

if [ "$FVEOPTONOFF" = "OFF" ]; then
	OFF='Y'
fi

while [ $# -gt 0 ]; do
	case $1 in
		-h|--help) printHelp; shift;;
		--off) OFF='Y' ; shift;;
		-v|--verbose) VERB=Y; VERBOUT='' ; shift;;
		-d|--debug) VERB=Y; VERBOUT=''; DEBUG=Y ; shift;;
		-f|--force) FORCE='Y'; shift;;
		*)  echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
	esac
done

checkUptime

getAvrg

#AVRG=0

ENERGYBUCKET=$AVRG

#checkTDstatus

mainLoop


rm -f "$TMPDIR"/FVE.statuses
exit 0
