#!/bin/bash

PNGC=1
PNGW=10
DEST=8.8.8.8


if ( ! ping -q -c $PNGC -w $PNGW $DEST >> /dev/null ); then
	sudo shutdown -r now
fi

if [ $(free -m | awk  /-/'{print $NF}') -le 100 ]; then
	sudo shutdown -r now
fi
