#! /bin/bash
### BEGIN INIT INFO
# Provides:          telldusd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Telldusd
# Description:       Telldus TellStick background service
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Telldus TellStick background service"
NAME=telldusd
DAEMON=/usr/sbin/$NAME
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

do_start()
{	
	telldusd || return 1
}

get_status() {
    DPID=$(ps -ef | grep -v bash | grep -v grep |  grep telldusd | awk '{print $2}')
    if [ "$DPID" ]; then
		echo "Running with pid $DPID"
		exit 0
    else
		echo "Stopped"
		exit 1
    fi
}

do_stop()
{
	kill -9 $(ps -ef | grep -v bash | grep -v grep |  grep telldusd | awk '{print $2}')
}


do_reload() {
	do_stop
	sleep 1
	do_start
	
	return 0
}

case "$1" in
  start) do_start; get_status; exit 0 ;;
  stop) do_stop; get_status; exit 0 ;;
  restart|force-reload) do_reload; exit 0 ;;
  status) get_status; exit 0;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}"
	exit 3
	;;
esac
